version: '3'

services:
  python:
    build: ./.devcontainer
    container_name: python
    volumes:
      - .:/home/pyusr
  selenium:
    image: selenium/standalone-chrome-debug:latest
    container_name: selenium
    ports:
      - 4444:4444
      - 5900:5900

